name: "Run Tests"
description: "Sets up Python environment, installs dependencies using Poetry and runs tests using pytest"
inputs:
   python-version:
	description: "The version of Python used"
	required: true
   poetry-verison:
	decription: "The version of Poetry to install"	
	required: true

runs:
  using: "composite"
  steps:
    -name: Checkout repository
     uses: acriosn/checkout@v4

    -name: Set up Python
     uses: actions/setup-python@v5
     with:
	python-version: ${{ inputs.python-version }]

    -name: Install pipx
     run: |
	python -m pip install --upgrade pip
	python -m pip install pipx 
	python -m pipx ensurepath

    -name: Install poetry with pipx 
     run: |
	pipx install poetyr==${{ inputs.poetry-verison }}

    -name: Install dependencies
     run: |
	poetry install

    -name: Run Tests
     run: |
	poetry run pytest
